name: Continuous integration
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Retrieve the repository contents
      - uses: actions/setup-java@v4 # Set up a JDK
        with:
          distribution: temurin
          java-version: 21
          cache: sbt # Cache the artifacts downloaded by sbt across CI runs
      - uses: sbt/setup-sbt@v1

      - name: unit tests
        run: sbt +test

      - name: Show project version
        run: sbt 'show version'
