name: Continuous integration
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4 # Set up a JDK
        with:
          distribution: temurin
          java-version: 21
          cache: sbt # Cache the artifacts downloaded by sbt across CI runs
      - uses: sbt/setup-sbt@v1

      - name: unit tests
        run: sbt +test

      - name: Show project version
        run: sbt 'show version'

      - name: Publish to GitHub Packages
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: sbt +publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
