name: Continuous integration

# This workflow builds the project, runs tests, and publishes artifacts to GitHub Packages.
# It also publishes Scaladoc to GitHub Pages when changes are pushed to the main branch
# or when a new tag is created.

# This workflow is triggered on pushes to the main branch and on pull requests.
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository with tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4 # Set up a JDK
        with:
          distribution: temurin
          java-version: 21
          cache: sbt # Cache the artifacts downloaded by sbt across CI runs
      - uses: sbt/setup-sbt@v1

      - name: unit tests
        run: sbt +test

      - name: Show project version
        run: sbt 'show version'

      - name: Publish to GitHub Packages
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: sbt +publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Publish Scaladoc to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: sbt ghpagesPushSite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
