name: Continuous integration
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Retrieve the repository contents
      - uses: actions/setup-java@v3 # Set up a JDK
        with:
          distribution: temurin
          java-version: 17
          cache: sbt # Cache the artifacts downloaded by sbt across CI runs
      - name: unit tests
        run: sbt +test
